# ===== STAGE 1: build =====
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# ===== STAGE 2: production =====
FROM node:20-alpine

ENV NODE_ENV=production

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/package.json ./package.json

# Встановлюємо лише продакшн-залежності
RUN npm ci --omit=dev

# За замовчуванням запускає головного worker (можна перевизначити в compose)
CMD ["node", "dist/rabbitmq.subscription-confirmation.js"]
