version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
    container_name: climatic_api_prod
    command: node dist/main.js
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
