version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_prod
      target: production
      args:
        NODE_ENV: production
    container_name: climatic_api_prod
    ports:
      - '3000:3000'
    env_file:
      - .env.prod
    depends_on:
      - postgres
    restart: unless-stopped
    networks:
      - climatic_net

  postgres:
    image: postgres:15
    container_name: climatic_db_prod
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    env_file:
      - .env.prod
    networks:
      - climatic_net

volumes:
  pg_data_prod:

networks:
  climatic_net:
    driver: bridge
