# ───── STAGE 1: build ─────
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./
RUN npm ci

COPY . .
RUN npm run build

# ───── STAGE 2: production ─────
FROM node:20-alpine

ENV NODE_ENV=production

WORKDIR /app

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

# додатково копіюємо конфіг для CLI TypeORM
COPY --from=builder /app/tsconfig.build.json ./tsconfig.build.json
COPY --from=builder /app/src/infrastructure/database ./src/infrastructure/database

# Запуск міграцій та застосунку
CMD ["sh", "-c", "npx typeorm migration:run -d dist/infrastructure/database/typeorm.config.js && node dist/main.js"]
