version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: climatic_api_dev
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www/application
    env_file:
      - .env
    depends_on:
      - postgres
      - redis

  redis:
    image: redis
    ports:
      - '6379:6379'

  postgres:
    image: postgres:15
    container_name: climatic_db_dev
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  redis:
    driver: local
