version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_prod
    container_name: climatic_api_prod
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production

  postgres:
    image: postgres:15
    container_name: climatic_db_prod
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.prod
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${DB_USERNAME} -d ${DB_NAME}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: climatic_redis_prod
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env.prod
    volumes:
      - redis_data_prod:/data

volumes:
  pg_data_prod:
  redis_data_prod:
