# ===== STAGE 1: build =====
FROM node:20-alpine AS builder

WORKDIR /var/www/application

COPY package*.json ./

RUN npm ci

COPY . .

RUN npm run build

# ===== STAGE 2: production =====
FROM node:20-alpine

ENV NODE_ENV=production

WORKDIR /var/www/application

COPY --from=builder /var/www/application/dist ./dist
COPY --from=builder /var/www/application/package.json ./package.json
COPY --from=builder /var/www/application/package-lock.json ./package-lock.json
COPY --from=builder /var/www/application/src/infrastructure/mail/templates ./src/infrastructure/mail/templates

# Встановлюємо лише продакшн-залежності
RUN npm ci --omit=dev

# За замовчуванням запускає головного worker (можна перевизначити в compose)
CMD ["node", "dist/rabbitmq.subscription-confirmation.js"]
