version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile_prod
    container_name: climatic_api_prod
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production

  postgres:
    image: postgres:15
    container_name: climatic_db_prod
    restart: always
    ports:
      - '5432:5432'
    env_file:
      - .env.prod
    volumes:
      - pg_data_prod:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: climatic_redis_prod
    restart: always
    ports:
      - '6379:6379'
    env_file:
      - .env.prod
    volumes:
      - redis_data_prod:/data

  rabbitmq:
    image: rabbitmq:3.13-management
    restart: unless-stopped
    ports:
      - '5672:5672' # AMQP
      - '15672:15672' # Web UI
    env_file:
      - .env.prod
    volumes:
      - rabbitmqdata_prod:/var/lib/rabbitmq

  # Мікросервіс підтвердження підписки
  subscription_confirmation_worker:
    container_name: subscription_confirmation_worker
    build:
      context: .
      dockerfile: Dockerfile_worker
    command: ['node', 'dist/rabbitmq.subscription-confirmation.main.js']
    depends_on:
      - rabbitmq

  # Мікросервіс для щоденної розсилки
  weather_daily_worker:
    container_name: weather_daily_worker
    build:
      context: .
      dockerfile: Dockerfile_worker
    command: ['node', 'dist/rabbitmq.weather-daily.main.js']
    depends_on:
      - rabbitmq

  # Мікросервіс для погодинної розсилки
  weather_hourly_worker:
    container_name: weather_hourly_worker
    build:
      context: .
      dockerfile: Dockerfile_worker
    command: ['node', 'dist/rabbitmq.weather-hourly.main.js']
    depends_on:
      - rabbitmq

volumes:
  pg_data_prod:
  redis_data_prod:
  rabbitmqdata_prod:
