export enum ClientNames {
  SUBSCRIPTION_CONFIRMATION_MAIL = 'SUBSCRIPTION_CONFIRMATION_MAIL',
  WEATHER_UPDATE_HOURLY_MAIL = 'WEATHER_UPDATE_HOURLY_MAIL',
  WEATHER_UPDATE_DAILY_MAIL = 'WEATHER_UPDATE_DAILY_MAIL',
}
